# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CommentDiary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommentDiary
    pod 'FSCalendar'
pod 'AlamofireNetworkActivityIndicator', '~> 3.1'
pod 'Alamofire'
    pod 'SnapKit', '~> 5.0.0'
pod 'PanModal'
pod 'IQKeyboardManagerSwift'
pod 'Siren'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
pod 'Then'
end
